- name: create disks
  google.cloud.gcp_compute_disk:
    name: disk-instance
    size_gb: 500
    zone: "{{instances[0].gce_zone}}"
    project: "{{instances[0].gce_project}}"
    auth_kind: serviceaccount
    service_account_file: "{{service_account_file}}"
    source_image: "{{instances[0].gce_source_image}}"
    type:  pd-ssd
    state: present
  register: disk




- name: create instance
  google.cloud.gcp_compute_instance:
    name: "{{instances[0].name}}"
    machine_type: "{{instances[0].gce_machine_type}}"
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ disk }}"
    network_interfaces:
    - network:
        selfLink: global/networks/default     
    metadata:
      managed-by: "Ansible"
      ssh-keys: ":\n"
    zone: "{{instances[0].gce_zone}}"
    project: "{{instances[0].gce_project}}"
    auth_kind: serviceaccount
    service_account_file: "{{service_account_file}}"
    state: present
    status: RUNNING
  register: gce_instance
  
